--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Arisify/GeometryLib
build-by-default: true
branches:
- master
projects:
  GeometryLib:
    path: ""
    model: virion
    type: library
...
